name: Unit tests

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: mcr.microsoft.com/azure-sql-edge
    steps:
      - uses: actions/checkout@master
      - name: Setup sqltest
        run: dotnet tool install -g dotnet-sqltest
      - name: Pull image
        run: docker pull ${{ env.IMAGE_NAME }}
      - name: Build tests
        run: dotnet build latest/Tests
      - name: Run tests
        run: sqltest runall -p latest/Tests -i ${{ env.IMAGE_NAME }} -c Polish_CI_AS
