name: Unit tests

on:
  pull_request:
  push:
    branches:
    - main
    paths:
    - '*'
    - '!/docs/*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - 1433/tcp
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: "StrongP@ssw0rd!"
    steps:
      - uses: actions/checkout@master
      - name: Setup dotnet
        uses: actions/setup-dotnet@master
        with:
          dotnet-version: '6.0'
      - name: Run unit tests
        run: Invoke-SQlCmd -ServerInstance "localhost,1433" -Database "master"" -username "sa"" -Password "StrongP@ssw0rd!" -InputFile "./src/tSQLt.Helper_TurnIntoDataRow.sql" -ConnectionTieout 120