name: Unit tests

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - 1433/tcp
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: "StrongP@ssw0rd!"
    steps:
      - uses: actions/checkout@master
      - name: Install-Module SqlServer
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module -Name SqlServer
      - name: Create objects
        shell: pwsh
        run: Invoke-SqlCmd -ServerInstance "localhost,${{ job.services.sqlserver.ports[1433] }}" -Database "master" -username "sa" -Password "StrongP@ssw0rd!" -ConnectionTimeout 30 -InputFile "./src/tSQLt.Helper_TurnIntoDataRow.sql"
      - name: Run unit tests
        shell: pwsh
        run: Invoke-SqlCmd -ServerInstance "localhost,${{ job.services.sqlserver.ports[1433] }}" -Database "master" -username "sa" -Password "StrongP@ssw0rd!" -ConnectionTimeout 30 -InputFile "./test/testHelperTurnIntoDataRow.sql"
