name: Unit tests

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - 1433/tcp
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: "StrongP@ssw0rd!"
    steps:
      - uses: actions/checkout@master
      - name: Setup dotnet
        uses: actions/setup-dotnet@master
        with:
          dotnet-version: '6.0'
      - name: Build tests
        run: dotnet build Tests
      - name: Publish tests
        run: dotnet publish Tests /p:TargetDatabaseName=Tests /p:TargetUser=sa /p:TargetPassword=StrongP@ssw0rd! /p:TargetPort=${{ job.services.sqlserver.ports[1433] }}
      - name: Run unit tests
        run: sqlcmd -S localhost,${{ job.services.sqlserver.ports[1433] }} -d Tests -U sa -P StrongP@ssw0rd! -t 30 -Q "exec testConvertIntoInserts.test1"
